### ISSUE TITLE
err

### ISSUE THREAD

**Issue by tujhTujhov** [ExoNarcis/GoLoggerService#2]
https://github.com/ExoNarcis/GoLoggerService/blob/0cf52bea732bd991718aa43df6f446d150accd86/LoggerServiceServer.go#L38
в го приянто использовать для error название переменной `err`, а не `errW` или `err0`

**Comment by ExoNarcis** [comment]
Закрыто с https://github.com/ExoNarcis/GoLoggerService/commit/37592dca47da0563c2f5bcec8d97c63b10a16fe9
